# 开发环境配置
springdoc:
  paths-to-match: /api/**
  swagger-ui:
    operations-sorter: alpha
spring:
  influx:
    url: http://47.97.2.37:8086
    user: admin
    password: ai532104
  mail:
    host: smtp.163.com
    username: Javastudy1@163.com
    password: YUVRVNKZTTIUMADI
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
       mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    addresses: 47.97.2.37
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
  data:
    redis:
      database: 0
      host: 47.97.2.37
      username: default
      password: redis_HrDCXN
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql_QR62KR
    url: jdbc:mysql://47.97.2.37:3306/monitor
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 50
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
